// <auto-generated />
using KisVuzDotNetCore2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KisVuzDotNetCore2.Migrations
{
    [DbContext(typeof(AppIdentityDBContext))]
    [Migration("20180620133723_Ebs")]
    partial class Ebs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("KisVuzDotNetCore2.Models.AcademicDegree", b =>
                {
                    b.Property<int>("AcademicDegreeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcademicDegreeGroupId");

                    b.Property<string>("AcademicDegreeName");

                    b.HasKey("AcademicDegreeId");

                    b.HasIndex("AcademicDegreeGroupId");

                    b.ToTable("AcademicDegrees");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.AcademicDegreeGroup", b =>
                {
                    b.Property<int>("AcademicDegreeGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcademicDegreeGroupName");

                    b.HasKey("AcademicDegreeGroupId");

                    b.ToTable("AcademicDegreeGroups");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.AcademicStat", b =>
                {
                    b.Property<int>("AcademicStatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcademicStatName");

                    b.HasKey("AcademicStatId");

                    b.ToTable("AcademicStats");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AcademicDegreeId");

                    b.Property<int?>("AcademicStatId");

                    b.Property<int>("AccessFailedCount");

                    b.Property<byte[]>("AppUserPhoto");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("DateStartWorking");

                    b.Property<DateTime?>("DateStartWorkingSpec");

                    b.Property<int?>("EduLevelGroupId");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Patronymic");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AcademicDegreeId");

                    b.HasIndex("AcademicStatId");

                    b.HasIndex("EduLevelGroupId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduAccred", b =>
                {
                    b.Property<int>("EduAccredId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EduAccredDate");

                    b.Property<DateTime>("EduAccredDateExpiration");

                    b.Property<int?>("EduAccredFileId");

                    b.Property<string>("EduAccredNumber");

                    b.HasKey("EduAccredId");

                    b.HasIndex("EduAccredFileId");

                    b.ToTable("EduAccreds");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduChislen", b =>
                {
                    b.Property<int>("EduChislenId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EduFormId");

                    b.Property<int>("EduProfileId");

                    b.Property<int>("NumberBFpriem");

                    b.Property<int>("NumberBMpriem");

                    b.Property<int>("NumberBRpriem");

                    b.Property<int>("NumberPpriem");

                    b.HasKey("EduChislenId");

                    b.HasIndex("EduFormId");

                    b.HasIndex("EduProfileId");

                    b.ToTable("EduChislens");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduForm", b =>
                {
                    b.Property<int>("EduFormId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EduFormName");

                    b.HasKey("EduFormId");

                    b.ToTable("EduForms");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduKurs", b =>
                {
                    b.Property<int>("EduKursId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EduKursName");

                    b.Property<int>("EduKursNumber");

                    b.HasKey("EduKursId");

                    b.ToTable("EduKurses");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduLevel", b =>
                {
                    b.Property<int>("EduLevelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EduLevelName");

                    b.HasKey("EduLevelId");

                    b.ToTable("EduLevels");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduNapravl", b =>
                {
                    b.Property<int>("EduNapravlId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EduNapravlCode");

                    b.Property<string>("EduNapravlName");

                    b.Property<string>("EduNapravlStandartDocLink");

                    b.Property<int>("EduUgsId");

                    b.HasKey("EduNapravlId");

                    b.HasIndex("EduUgsId");

                    b.ToTable("EduNapravls");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduPlan", b =>
                {
                    b.Property<int>("EduPlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EduFormId");

                    b.Property<int>("EduProfileId");

                    b.Property<int?>("EduYearBeginningTrainingId");

                    b.Property<int?>("EduYearId");

                    b.Property<int>("StructKafId");

                    b.HasKey("EduPlanId");

                    b.HasIndex("EduFormId");

                    b.HasIndex("EduProfileId");

                    b.HasIndex("EduYearBeginningTrainingId");

                    b.HasIndex("EduYearId");

                    b.HasIndex("StructKafId");

                    b.ToTable("EduPlans");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduProfile", b =>
                {
                    b.Property<int>("EduProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EduNapravlId");

                    b.Property<string>("EduProfileName");

                    b.HasKey("EduProfileId");

                    b.HasIndex("EduNapravlId");

                    b.ToTable("EduProfiles");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduUgs", b =>
                {
                    b.Property<int>("EduUgsId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EduAccredId");

                    b.Property<int>("EduLevelId");

                    b.Property<string>("EduUgsCode");

                    b.Property<string>("EduUgsName");

                    b.HasKey("EduUgsId");

                    b.HasIndex("EduAccredId");

                    b.HasIndex("EduLevelId");

                    b.ToTable("EduUgses");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduYear", b =>
                {
                    b.Property<int>("EduYearId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EduYearName");

                    b.HasKey("EduYearId");

                    b.ToTable("EduYears");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduYearBeginningTraining", b =>
                {
                    b.Property<int>("EduYearBeginningTrainingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EduYearBeginningTrainingName");

                    b.HasKey("EduYearBeginningTrainingId");

                    b.ToTable("EduYearBeginningTrainings");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.EduLevelGroup", b =>
                {
                    b.Property<int>("EduLevelGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EduLevelGroupName");

                    b.HasKey("EduLevelGroupId");

                    b.ToTable("EduLevelGroups");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.FileDataType", b =>
                {
                    b.Property<int>("FileDataTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FileDataTypeGroupId");

                    b.Property<string>("FileDataTypeName");

                    b.Property<string>("Itemprop");

                    b.HasKey("FileDataTypeId");

                    b.HasIndex("FileDataTypeGroupId");

                    b.ToTable("FileDataTypes");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.FileDataTypeGroup", b =>
                {
                    b.Property<int>("FileDataTypeGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileDataTypeGroupName");

                    b.HasKey("FileDataTypeGroupId");

                    b.ToTable("FileDataTypeGroups");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<string>("FileName");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<DateTime>("UploadDate");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.FileToFileType", b =>
                {
                    b.Property<int>("FileToFileTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FileDataTypeId");

                    b.Property<int>("FileModelId");

                    b.HasKey("FileToFileTypeId");

                    b.HasIndex("FileDataTypeId");

                    b.HasIndex("FileModelId");

                    b.ToTable("FileToFileTypes");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Priem.Vacant", b =>
                {
                    b.Property<int>("VacantId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EduFormId");

                    b.Property<int>("EduKursId");

                    b.Property<int>("EduNapravlId");

                    b.Property<int>("NumberBFVacant");

                    b.Property<int>("NumberBMVacant");

                    b.Property<int>("NumberBRVacant");

                    b.Property<int>("NumberPVacant");

                    b.HasKey("VacantId");

                    b.HasIndex("EduFormId");

                    b.HasIndex("EduKursId");

                    b.HasIndex("EduNapravlId");

                    b.ToTable("Vacants");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<string>("NapravlName");

                    b.Property<string>("QualificationName");

                    b.Property<int?>("RowStatusId");

                    b.HasKey("QualificationId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("RowStatusId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.RowStatus", b =>
                {
                    b.Property<int>("RowStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RowStatusName");

                    b.HasKey("RowStatusId");

                    b.ToTable("RowStatuses");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("HouseNumber");

                    b.Property<string>("PostCode");

                    b.Property<string>("Region");

                    b.Property<string>("Settlement");

                    b.Property<string>("Street");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailComment");

                    b.Property<string>("EmailValue");

                    b.Property<int?>("StructInstituteId");

                    b.Property<int?>("StructUniversityId");

                    b.HasKey("EmailId");

                    b.HasIndex("StructInstituteId");

                    b.HasIndex("StructUniversityId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Fax", b =>
                {
                    b.Property<int>("FaxId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FaxComment");

                    b.Property<string>("FaxValue");

                    b.Property<int?>("StructInstituteId");

                    b.Property<int?>("StructUniversityId");

                    b.HasKey("FaxId");

                    b.HasIndex("StructInstituteId");

                    b.HasIndex("StructUniversityId");

                    b.ToTable("Faxes");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PostName");

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructFacultet", b =>
                {
                    b.Property<int>("StructFacultetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("StructInstituteId");

                    b.Property<int>("StructSubvisionId");

                    b.HasKey("StructFacultetId");

                    b.HasIndex("StructInstituteId");

                    b.HasIndex("StructSubvisionId");

                    b.ToTable("StructFacultets");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructInstitute", b =>
                {
                    b.Property<int>("StructInstituteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<DateTime>("DateOfCreation");

                    b.Property<bool>("ExistenceOfFilials");

                    b.Property<string>("StructInstituteName");

                    b.Property<int>("UniversityId");

                    b.Property<string>("WorkingRegime");

                    b.Property<string>("WorkingSchedule");

                    b.HasKey("StructInstituteId");

                    b.HasIndex("AddressId");

                    b.HasIndex("UniversityId");

                    b.ToTable("StructInstitutes");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructKaf", b =>
                {
                    b.Property<int>("StructKafId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("StructFacultetId");

                    b.Property<int>("StructSubvisionId");

                    b.HasKey("StructKafId");

                    b.HasIndex("StructFacultetId");

                    b.HasIndex("StructSubvisionId");

                    b.ToTable("StructKafs");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructSubvision", b =>
                {
                    b.Property<int>("StructSubvisionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("StructStandingOrderId");

                    b.Property<int>("StructSubvisionAdressId");

                    b.Property<int?>("StructSubvisionEmailId");

                    b.Property<string>("StructSubvisionFioChief");

                    b.Property<string>("StructSubvisionName");

                    b.Property<int>("StructSubvisionPostChiefId");

                    b.Property<string>("StructSubvisionSite");

                    b.Property<int>("StructSubvisionTypeId");

                    b.HasKey("StructSubvisionId");

                    b.HasIndex("StructStandingOrderId");

                    b.HasIndex("StructSubvisionAdressId");

                    b.HasIndex("StructSubvisionEmailId");

                    b.HasIndex("StructSubvisionPostChiefId");

                    b.HasIndex("StructSubvisionTypeId");

                    b.ToTable("StructSubvisions");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructSubvisionType", b =>
                {
                    b.Property<int>("StructSubvisionTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StructSubvisionTypeName");

                    b.HasKey("StructSubvisionTypeId");

                    b.ToTable("StructSubvisionTypes");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructUniversity", b =>
                {
                    b.Property<int>("StructUniversityId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<DateTime>("DateOfCreation");

                    b.Property<bool>("ExistenceOfFilials");

                    b.Property<string>("StructUniversityName");

                    b.Property<string>("WorkingRegime");

                    b.Property<string>("WorkingSchedule");

                    b.HasKey("StructUniversityId");

                    b.HasIndex("AddressId");

                    b.ToTable("StructUniversities");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Telephone", b =>
                {
                    b.Property<int>("TelephoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("StructInstituteId");

                    b.Property<int?>("StructUniversityId");

                    b.Property<string>("TelephoneComment");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("TelephoneId");

                    b.HasIndex("StructInstituteId");

                    b.HasIndex("StructUniversityId");

                    b.ToTable("Telephones");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Sveden.ElectronBiblSystem", b =>
                {
                    b.Property<int>("ElectronBiblSystemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CopyDogovorId");

                    b.Property<DateTime?>("DateEnd");

                    b.Property<DateTime>("DateStart");

                    b.Property<string>("LinkEbs");

                    b.Property<string>("NameEbs");

                    b.Property<string>("NumberDogovor");

                    b.HasKey("ElectronBiblSystemId");

                    b.HasIndex("CopyDogovorId");

                    b.ToTable("ElectronBiblSystem");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Sveden.HostelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Itemprop");

                    b.Property<string>("Link");

                    b.Property<string>("NameIndicator");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("HostelInfo");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Sveden.Rucovodstvo", b =>
                {
                    b.Property<int>("RucovodstvoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Fio");

                    b.Property<string>("Post");

                    b.Property<string>("Telephone");

                    b.HasKey("RucovodstvoId");

                    b.ToTable("SvedenRucovodstvo");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Sveden.RucovodstvoFil", b =>
                {
                    b.Property<int>("RucovodstvoFilId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Fio");

                    b.Property<string>("NameFil");

                    b.Property<string>("Post");

                    b.Property<string>("Telephone");

                    b.HasKey("RucovodstvoFilId");

                    b.ToTable("RucovodstvoFil");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Sveden.Volume", b =>
                {
                    b.Property<int>("VolumeId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("FinBFVolume");

                    b.Property<double>("FinBMVolume");

                    b.Property<double>("FinBRVolume");

                    b.Property<double>("FinPVolume");

                    b.HasKey("VolumeId");

                    b.ToTable("Volume");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Users.ProfessionalRetraining", b =>
                {
                    b.Property<int>("ProfessionalRetrainingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<string>("ProfessionalRetrainingCity");

                    b.Property<DateTime>("ProfessionalRetrainingDateFinish");

                    b.Property<DateTime>("ProfessionalRetrainingDateIssue");

                    b.Property<DateTime>("ProfessionalRetrainingDateStart");

                    b.Property<string>("ProfessionalRetrainingDiplomNumber");

                    b.Property<string>("ProfessionalRetrainingDiplomRegNumber");

                    b.Property<int>("ProfessionalRetrainingFileId");

                    b.Property<int>("ProfessionalRetrainingHours");

                    b.Property<string>("ProfessionalRetrainingInstitition");

                    b.Property<string>("ProfessionalRetrainingProgramName");

                    b.HasKey("ProfessionalRetrainingId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProfessionalRetrainingFileId");

                    b.ToTable("ProfessionalRetrainings");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Users.RefresherCourse", b =>
                {
                    b.Property<int>("RefresherCourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<string>("RefresherCourseCity");

                    b.Property<DateTime>("RefresherCourseDateFinish");

                    b.Property<DateTime>("RefresherCourseDateIssue");

                    b.Property<DateTime>("RefresherCourseDateStart");

                    b.Property<int>("RefresherCourseFileId");

                    b.Property<int>("RefresherCourseHours");

                    b.Property<string>("RefresherCourseInstitition");

                    b.Property<string>("RefresherCourseName");

                    b.Property<string>("RefresherCourseRegNumber");

                    b.HasKey("RefresherCourseId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("RefresherCourseFileId");

                    b.ToTable("RefresherCourses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.AcademicDegree", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AcademicDegreeGroup", "AcademicDegreeGroup")
                        .WithMany("AcademicDegrees")
                        .HasForeignKey("AcademicDegreeGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.AppUser", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AcademicDegree", "AcademicDegree")
                        .WithMany()
                        .HasForeignKey("AcademicDegreeId");

                    b.HasOne("KisVuzDotNetCore2.Models.AcademicStat", "AcademicStat")
                        .WithMany()
                        .HasForeignKey("AcademicStatId");

                    b.HasOne("KisVuzDotNetCore2.Models.EduLevelGroup", "EduLevelGroup")
                        .WithMany()
                        .HasForeignKey("EduLevelGroupId");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduAccred", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.FileModel", "EduAccredFile")
                        .WithMany()
                        .HasForeignKey("EduAccredFileId");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduChislen", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduForm", "EduForm")
                        .WithMany()
                        .HasForeignKey("EduFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduProfile", "EduProfile")
                        .WithMany()
                        .HasForeignKey("EduProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduNapravl", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduUgs", "EduUgs")
                        .WithMany("EduNapravls")
                        .HasForeignKey("EduUgsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduPlan", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduForm", "EduForm")
                        .WithMany()
                        .HasForeignKey("EduFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduProfile", "EduProfile")
                        .WithMany("EduPlans")
                        .HasForeignKey("EduProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduYearBeginningTraining", "EduYearBeginningTraining")
                        .WithMany()
                        .HasForeignKey("EduYearBeginningTrainingId");

                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduYear", "EduYear")
                        .WithMany()
                        .HasForeignKey("EduYearId");

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructKaf", "StructKaf")
                        .WithMany()
                        .HasForeignKey("StructKafId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduProfile", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduNapravl", "EduNapravl")
                        .WithMany("EduProfiles")
                        .HasForeignKey("EduNapravlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Education.EduUgs", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduAccred", "EduAccred")
                        .WithMany("EduAccredUgses")
                        .HasForeignKey("EduAccredId");

                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduLevel", "EduLevel")
                        .WithMany("EduUgses")
                        .HasForeignKey("EduLevelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.FileDataType", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.FileDataTypeGroup", "FileDataTypeGroup")
                        .WithMany("FileDataTypes")
                        .HasForeignKey("FileDataTypeGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.FileToFileType", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.FileDataType", "FileDataType")
                        .WithMany("FileToFileTypes")
                        .HasForeignKey("FileDataTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.FileModel", "FileModel")
                        .WithMany("FileToFileTypes")
                        .HasForeignKey("FileModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Priem.Vacant", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduForm", "EduForm")
                        .WithMany()
                        .HasForeignKey("EduFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduKurs", "EduKurs")
                        .WithMany()
                        .HasForeignKey("EduKursId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Education.EduNapravl", "EduNapravl")
                        .WithMany()
                        .HasForeignKey("EduNapravlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Qualification", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AppUser", "AppUser")
                        .WithMany("Qualifications")
                        .HasForeignKey("AppUserId");

                    b.HasOne("KisVuzDotNetCore2.Models.RowStatus", "RowStatus")
                        .WithMany()
                        .HasForeignKey("RowStatusId");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Email", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructInstitute")
                        .WithMany("Emailes")
                        .HasForeignKey("StructInstituteId");

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructUniversity")
                        .WithMany("Emailes")
                        .HasForeignKey("StructUniversityId");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Fax", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructInstitute")
                        .WithMany("Faxes")
                        .HasForeignKey("StructInstituteId");

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructUniversity")
                        .WithMany("Faxes")
                        .HasForeignKey("StructUniversityId");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructFacultet", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructInstitute", "StructInstitute")
                        .WithMany("StructFacultets")
                        .HasForeignKey("StructInstituteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructSubvision", "StructSubvision")
                        .WithMany()
                        .HasForeignKey("StructSubvisionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructInstitute", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Struct.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructUniversity", "University")
                        .WithMany("StructInstitutes")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructKaf", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructFacultet", "StructFacultet")
                        .WithMany()
                        .HasForeignKey("StructFacultetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructSubvision", "StructSubvision")
                        .WithMany()
                        .HasForeignKey("StructSubvisionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructSubvision", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.FileModel", "StructStandingOrder")
                        .WithMany()
                        .HasForeignKey("StructStandingOrderId");

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.Address", "StructSubvisionAdress")
                        .WithMany()
                        .HasForeignKey("StructSubvisionAdressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.Email", "StructSubvisionEmail")
                        .WithMany()
                        .HasForeignKey("StructSubvisionEmailId");

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.Post", "StructSubvisionPostChief")
                        .WithMany()
                        .HasForeignKey("StructSubvisionPostChiefId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructSubvisionType", "StructSubvisionType")
                        .WithMany("StructSubvisions")
                        .HasForeignKey("StructSubvisionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.StructUniversity", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Struct.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Struct.Telephone", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructInstitute")
                        .WithMany("Telephones")
                        .HasForeignKey("StructInstituteId");

                    b.HasOne("KisVuzDotNetCore2.Models.Struct.StructUniversity")
                        .WithMany("Telephones")
                        .HasForeignKey("StructUniversityId");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Sveden.ElectronBiblSystem", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.FileModel", "CopyDogovor")
                        .WithMany()
                        .HasForeignKey("CopyDogovorId");
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Users.ProfessionalRetraining", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AppUser", "AppUser")
                        .WithMany("ProfessionalRetrainings")
                        .HasForeignKey("AppUserId");

                    b.HasOne("KisVuzDotNetCore2.Models.FileModel", "ProfessionalRetrainingFile")
                        .WithMany()
                        .HasForeignKey("ProfessionalRetrainingFileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KisVuzDotNetCore2.Models.Users.RefresherCourse", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AppUser", "AppUser")
                        .WithMany("RefresherCourses")
                        .HasForeignKey("AppUserId");

                    b.HasOne("KisVuzDotNetCore2.Models.FileModel", "RefresherCourseFile")
                        .WithMany()
                        .HasForeignKey("RefresherCourseFileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisVuzDotNetCore2.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KisVuzDotNetCore2.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
